name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Tests (unit & functional)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: app-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Validate composer files
        run: composer validate

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Update composer
        run: composer self-update

      - name: install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --no-ansi

      - name: Prepare the Database
        run: sudo systemctl start postgresql

      ## @TODO: Add Coverage
      - name: PHPUnit Tests
        run: ./vendor/bin/phpunit src tests --testdox --debug
        env:
          APP_ENV: test
          DATABASE_URL: postgresql://app-test:password@127.0.0.1:${{ job.services.postgres.ports['5432'] }}/app_test?serverVersion=16&charset=utf8
          SYMFONY_DEPRECATIONS_HELPER: 999999
